read_more_copy = "Read more"
show_reading_time = true

[ananke.social.follow]
new_window_icon = true
networks = [
  "github"
]

[ananke.social.github]
username = "D14rn"
profileLink = "https://github.com/D14rn/blog"